-- Printers
E2Helper.Descriptions["isPrinter"] = "[Number] Returns 1 if the entity is a money printer, 0 if it isn't."
E2Helper.Descriptions["printerAmount"] = "[Number] Returns the amount of money stored in the money printer, -1 if the entity isn't a money printer."
E2Helper.Descriptions["printerType"] = "[String] Returns the type (or class) of the printer, "" if the entity isn't a money printer."
E2Helper.Descriptions["printerOwner"] = "[Entity] Returns the owner of the printer."
E2Helper.Descriptions["printerTier"] = "[String] Returns the tier of the printer."
E2Helper.Descriptions["printerInkAmount"] = "[Number] Returns the amount of ink in the printer."
E2Helper.Descriptions["printerInkMax"] = "[Number] Returns the max amount of ink the printer can hold."
E2Helper.Descriptions["printerHealth"] = "[Number] Returns the printers health."
E2Helper.Descriptions["printerHQCooling"] = "[Number] Returns 1 if the printer has HQ Cooling installed, otherwise it returns 0."

-- Money
E2Helper.Descriptions["isMoney"] = "[Number] Returns 1 if the entity is spawned / dropped money, 0 if it isn't."
E2Helper.Descriptions["moneyAmount"] = "[Number] Returns the amount of money dropped."

-- Shipments
E2Helper.Descriptions["isShipment"] = "[Number] Returns 1 if the entity is a shipment, 0 if it isn't."
E2Helper.Descriptions["shipmentName"] = "[String] Returns the name of the entity in the shipment."
E2Helper.Descriptions["shipmentClass"] = "[String] Returns the type (or class) of the entity in the shipment."
E2Helper.Descriptions["shipmentModel"] = "[String] Returns the model of the entity in the shipment."
E2Helper.Descriptions["shipmentAmount"] = "[Number] Returns the amount of entities currently in the shipment."
E2Helper.Descriptions["shipmentID"] = "[Number] Returns the ID of the entity in the shipment, generated by DarkRP."
E2Helper.Descriptions["shipmentCost"] = "[Number] Returns the buy price of the shipment."
E2Helper.Descriptions["shipmentIndividualCost"] = "[Number] Returns the buy price of a single entity in the shipment."
E2Helper.Descriptions["shipmentAvailableSeperately"] = "[Number] Returns 1 if the entity in the shipment can be bought seperately."
E2Helper.Descriptions["shipmentSpawnAmount"] = "[Number] Returns the amount of entities in the shipment when bought."
E2Helper.Descriptions["shipmentPricePerUnit"] = "[Number] Returns the price of 1 entity, when bought in a shipment (shipmentCost / shipmentAmount)."